<?xml version="1.0"?>
<root  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
 xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
 xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
 xmlns:xacro="http://ros.org/wiki/xacro" 
 name="Mantis">


<!-- =========================================================================================== -->
<!-- =========================================================================================== -->
<!-- =============================================PROPERTIES==================================== -->
<!-- =========================================================================================== -->
<!-- =========================================================================================== -->

	<xacro:property name="offset" value="0.02" />
	<xacro:property name="base_link_main_height" value="0.05058" />
	<xacro:property name="origin_to_elbow" value="0.104282" />
	<xacro:property name="joint_to_link" value="0.024" />
	<xacro:property name="link_length" value="0.1948" />
	<xacro:property name="pi" value="3.1415926535" />

<!-- =========================================================================================== -->
<!-- =========================================================================================== -->
<!-- =============================================MACROS======================================= -->
<!-- =========================================================================================== -->
<!-- =========================================================================================== -->

<!-- MACRO FOR THE ROBOT ARM -->
	<xacro:macro name="mantis_arm" params="parent *origin">

	<xacro:macro name="default_material">
        <mu1>100000</mu1>
        <mu2>100000</mu2>
	 	<kp>100.0</kp>
	 	<kd>0.01</kd>
	</xacro:macro>

	<gazebo reference="_main">
		<material>Gazebo/FlatBlack</material>
		<implicitSpringDamper>1</implicitSpringDamper>
		<xacro:default_material/>
	</gazebo>
	<gazebo reference="_housing">
		<material>Gazebo/Grey</material>
		<implicitSpringDamper>1</implicitSpringDamper>
		<xacro:default_material/>
	</gazebo>

	<xacro:macro name="default_damping_medium">
		<dynamics damping="0.25" friction="0.25"/>
	</xacro:macro>

<!-- Define the Macro for the main link  properties.They are shared by all three links, so we can define it here and use it for each portion. -->
<!-- params="orientation" -->
	<xacro:macro name="main_link" params="orientation">
		<origin xyz="0 0 ${link_length+3*joint_to_link}" rpy="${pi/2} 0 ${orientation}"/>
		<geometry>
			<mesh filename="package://mantis_sim/mesh/B2.dae"/>
		</geometry>
	</xacro:macro>
	
	<xacro:macro name="inertia_main_link" >
		<inertial>
			<mass value=".1155"/>
			<inertia ixx="0.00181" ixy="-0.3385E-6" ixz="-.00005688" iyy=".00781" iyz=".117E-5" izz="0.00008"/>
		</inertial>
	</xacro:macro>


<!-- Define the Macros for the joint housing mass properties. There exists 2 replica sets of joint housings, so we can define them here and use it for each portion. We can do the same for their meshes-->	
	<xacro:macro name="joint_link" >
		<origin xyz="0 ${2.5*offset} 0" rpy="0 ${pi} ${pi}" />
		<geometry>
			<mesh filename="package://mantis_sim/mesh/B3.dae"/>
		</geometry>
	</xacro:macro>

	<xacro:macro name="inertia_joint" >
		<inertial>
			<mass value=".146"/>
			<inertia ixx="0.0000306" ixy="0.62908934773947E-14" ixz="0.62908934773947E-14" iyy="0.0000495" iyz="0.62908934773947E-14" izz="0.0000443"/>
		</inertial>
	</xacro:macro>

<!-- =========================================================================================== -->
<!-- =========================================================================================== -->
<!-- =========================================LINKS============================================= -->
<!-- =========================================================================================== -->
<!-- =========================================================================================== -->

<!-- ======================= -->
<!-- Housing for the First Joint  -->
<!-- ======================= -->
	<link name="base_link_main">
<!-- 		<collision>
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0.02"/>
			<geometry>
				<mesh filename="package://mantis_sim/mesh/B0.dae"/>
			</geometry>
		</collision> -->
		<visual>
			<origin rpy="0.0 0.0 0.0" xyz="0 0 0.03"/>
			<geometry>
				<mesh filename="package://mantis_sim/mesh/B0.dae"/>
			</geometry>
		</visual>
		<inertial>
			<mass value="0.4004"/>
			<inertia ixx="0.0010733" ixy="-0.0000654" ixz="0.0001079" iyy="0.0012394" iyz="-0.000053" izz="0.0003487"/>
		</inertial>
	</link>


	<link name="base_roll_housing">
<!-- 		<collision>
			<origin rpy="0 0 0" xyz="0 0 0.02"/>
			<geometry>
				<mesh filename="package://mantis_sim/mesh/B1.dae"/>
			</geometry>
		</collision> -->
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0.02"/>
			<geometry>
				<mesh filename="package://mantis_sim/mesh/B1.dae"/>
			</geometry>
		</visual>
		<inertial>
			<mass value="0.064"/>
			<inertia ixx="0.00116" ixy="-1.62908934773947E-14" ixz="-1.62908934773947E-14" iyy="0.0115" iyz="-1.62908934773947E-14" izz="0.0094"/>
		</inertial>
	</link>

<!-- =======================
Link 1
======================= -->

	<link name="base_elbow">
<!-- 		<collision>
			<origin rpy="0 0 0" xyz="-${offset} -${offset} ${offset}"/>
			<geometry>
				<cylinder length=".045" radius=".02"/>
			</geometry>
		</collision> -->
		<visual>
			<origin rpy="0 ${pi/2} 0" xyz="-${offset} -${offset} ${offset}"/>
			<geometry>
				<mesh filename="package://mantis_sim/mesh/base_elbow.dae"/>
			</geometry>
		</visual>
		<inertial>
			<mass value="0.0386"/>
			<inertia ixx="0.00116" ixy="-1.62908934773947E-14" ixz="-1.62908934773947E-14" iyy="0.0115" iyz="-1.62908934773947E-14" izz="0.000094"/>
		</inertial>
	</link>

	<link name="link_one_main">
<!-- 		<collision>
			<xacro:main_link orientation="0"/>
		</collision> -->
		<visual>
			<xacro:main_link orientation="0"/>
		</visual>
		<xacro:inertia_main_link/>
	</link> 


<!-- =======================
Housing for Joint 2 
======================= -->


	<link name="joint_two_housing">
<!-- 		<collision>
			<xacro:joint_link/>
		</collision> -->
		<visual>
			<xacro:joint_link/>
		</visual>
		<xacro:inertia_joint/>
	</link> 



<!-- =======================
Link 2 
======================= -->


	<link name="link_two_main">
<!-- 		<collision>
			<xacro:main_link orientation="1.5707963"/>
		</collision> -->
		<visual>
			<xacro:main_link orientation="1.5707963"/>
		</visual>
		<xacro:inertia_main_link/>
	</link> 


<!-- ===== --><!-- ==================
Housing for Joint 3 
======================= -->


	<link name="joint_three_housing">
		<collision>
			<xacro:joint_link/>
		</collision>
		<visual>
			<xacro:joint_link/>
		</visual>
		<xacro:inertia_joint/>
	</link> 


<!-- =======================
Link 3 
======================= -->

	<link name="link_three_main">
<!-- 		<collision>
			<xacro:main_link orientation="1.5707963"/>
		</collision> -->
		<visual>
			<xacro:main_link orientation="1.5707963"/>
		</visual>
		<xacro:inertia_main_link/>
	</link> 

<!-- =======================
Housing for Wrist Joint 
======================= -->


	<link name="wrist_attach_point">
		<collision>
			<origin rpy="0 ${pi/2} ${pi/2}" xyz="0 ${1.5*offset} 0"/>
			<geometry>
				<mesh filename="package://mantis_sim/mesh/B8.dae"/>
			</geometry>
		</collision>
		<visual>
			<origin rpy="0 ${pi/2} ${pi/2}" xyz="0 ${1.5*offset} 0"/>
			<geometry>
				<mesh filename="package://mantis_sim/mesh/B8.dae"/>
			</geometry>
		</visual>
		<inertial>
			<mass value=".0184764"/>
			<inertia ixx="0.0052" ixy="1.62908934773947E-14" ixz="1.62908934773947E-14" iyy="0.0084" iyz="0.017" izz="0.0052"/>
		</inertial>
	</link> 



<!-- =========================================================================================== -->
<!-- =========================================================================================== -->
<!-- =========================================JOINTS============================================ -->
<!-- =========================================================================================== -->
<!-- =========================================================================================== -->

<!-- ======================= -->
<!-- roll 1 -->
<!-- ======================= -->


<joint name="roll_1" type="continuous"> 
 	<xacro:default_damping_medium/>			
	<axis xyz="0 0 1"/>
	<origin rpy="0 0 ${pi/2}" xyz="0 0 0"/>
	<parent link="base_link_main"/>
	<child link="base_roll_housing"/>
</joint>


<transmission name="roll_trans_1">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="roll_1">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="roll_mot_1">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</actuator>
</transmission>


<!-- ======================= -->
<!-- Elbow 1 -->
<!-- ======================= -->
<joint name="elbow_1" type="revolute"> 
 	<xacro:default_damping_medium/>			
	<axis xyz="0 1 0"/>
	<limit effort="1000.0" lower="-${pi}" upper="${pi}" velocity="0.25"/>
	<origin rpy="0 0 0" xyz="0 0 ${origin_to_elbow}"/>
	<parent link="base_roll_housing"/>
	<child link="base_elbow"/>
</joint>

<transmission name="elbow_trans_1">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="elbow_1">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="elbow_mot_1">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</actuator>
</transmission>


<!-- ======================= -->
<!-- Link 1 -->
<!-- ======================= -->


<joint name="link_1_A" type="fixed">
	<parent link="base_elbow"/>
	<child link="link_one_main"/>
</joint>


<!-- ======================= -->
<!-- Elbow 2 -->
<!-- ======================= -->


<joint name="elbow_2" type="revolute"> 
 	<xacro:default_damping_medium/>			
	<axis xyz="0 1 0"/>
	<limit effort="1000.0" lower="-${pi}" upper="${pi}" velocity="0.25"/>
	<origin rpy="0 0 0" xyz="0 0 ${link_length+3*joint_to_link}"/>
	<parent link="link_one_main"/>
	<child link="joint_two_housing"/>
</joint>


<transmission name="elbow_trans_2">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="elbow_2">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="elbow_mot_2">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</actuator>
</transmission>


<!-- ======================= -->
<!-- roll 2 -->
<!-- ======================= -->


<joint name="roll_2" type="continuous"> 
 	<xacro:default_damping_medium/>			
	<axis xyz="0 0 1"/>
	<origin rpy="0 0 0" xyz="0 ${2.5*offset} 0"/>
	<parent link="joint_two_housing"/>
	<child link="link_two_main"/>
</joint>

<transmission name="roll_trans_2">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="roll_2">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="roll_mot_2">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</actuator>
</transmission>



<!-- ======================= -->
<!-- Elbow 3 -->
<!-- ======================= -->


<joint name="elbow_3" type="revolute"> 
 	<xacro:default_damping_medium/>			
	<axis xyz="0 1 0"/>
	<limit effort="1000.0" lower="-${pi}" upper="${pi}" velocity="0.25"/>
	<origin rpy="0 0 -${pi/2}" xyz="0 0 ${link_length+3*joint_to_link}"/>
	<parent link="link_two_main"/>
	<child link="joint_three_housing"/>
</joint>

<transmission name="elbow_trans_3">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="elbow_3">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="elbow_mot_3">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</actuator>
</transmission>


<!-- ======================= -->
<!-- roll 3 -->
<!-- ======================= -->


<joint name="roll_3" type="continuous"> 
 	<xacro:default_damping_medium/>			
	<axis xyz="0 0 1"/>
	<origin rpy="0 0 0" xyz="0 ${2.5*offset} 0"/>
	<parent link="joint_three_housing"/>
	<child link="link_three_main"/>
</joint>

<transmission name="roll_trans_3">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="roll_3">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="roll_mot_3">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</actuator>
</transmission>



<!-- ======================= -->
<!-- Wrist -->
<!-- ======================= -->



<joint name="wrist" type="revolute"> 
 	<xacro:default_damping_medium/>			
	<axis xyz="0 1 0"/> 
	<limit effort="1000.0" lower="-${pi}" upper="0" velocity="0.25"/>
	<origin rpy="0 0 ${pi/2}" xyz="0 0 ${link_length+3*joint_to_link}"/>
	<parent link="link_three_main"/>
	<child link="wrist_attach_point"/>
</joint>


<transmission name="wrist_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="wrist">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="wrist_mot">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
	</actuator>
</transmission>


<!-- =============================== -->
<!-- GAZEBO SPECIFIC ADD ONS   -->
<!-- =============================== -->

<!-- =============================== -->
<!-- ROS_Control Plugin for Gazebo   -->
<!-- =============================== -->
<gazebo>
	<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
		<robotNamespace>/mantis</robotNamespace>
	</plugin>
</gazebo>


     <joint name="mantis_arm_joint" type="fixed">
		<xacro:insert_block name="origin" />
		<parent link="${parent}" />
        <child link="base_link_main" />
	</joint>
</xacro:macro>
</root>