#!/usr/bin/env python
# license removed for brevity
import rospy
from math import sin
from time import time
from std_msgs.msg import Float64

def mantis_joints():
    elbow1 = rospy.Publisher('mantis/elbow1_pos_control/command', Float64, queue_size=10)
    elbow2 = rospy.Publisher('mantis/elbow2_pos_control/command', Float64, queue_size=10)
    elbow3 = rospy.Publisher('mantis/elbow3_pos_control/command', Float64, queue_size=10)
    roll1 = rospy.Publisher('mantis/roll1_pos_control/command', Float64, queue_size=10)
    roll2 = rospy.Publisher('mantis/roll2_pos_control/command', Float64, queue_size=10)
    roll3 = rospy.Publisher('mantis/roll3_pos_control/command', Float64, queue_size=10)
    
    rospy.init_node('MANTIS_joints', anonymous=True)
    rate = rospy.Rate(10) # 10hz

    start = time()

    while not rospy.is_shutdown():

        elbow1.publish(3.14159/2)
        rate.sleep()

        elbow2.publish(3.14159)
        rate.sleep()

        elbow3.publish(3.14159)
        rate.sleep()



if __name__ == '__main__':
    # To run: rosrun mantis_sim MANTIS_example
    try:
        mantis_joints()
    except rospy.ROSInterruptException:
        pass