controller_list:
  - name: mantis/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - J1_roll
      - J2_pitch
      - J3_roll
      - J4_pitch
      - J5_roll
      - J6_pitch
      - J7_roll
      - J8_pitch
      - J9_wrist
      - J1_L_wrist
      - J1_R_wrist
      - J2_L_wrist
      - J2_R_wrist